feature - add a2c ppo algorithms
ReportFxxkingMan/MessyRL pull request #1
Opened 2022-08-04 14:14 UTC by rockgoat95

A2C 알고리즘 PPO 알고리즘 추가

2022-08-05 03:33 UTC, RektPunk reviewed
models/Reference/{model name} > models/{model_name} 으로 변경

2022-08-05 03:36 UTC, RektPunk requested changes
- 폴더명에 대문자 소문자로 변경
- A2C/a2c_learn.py >> a2c/learn.py 로 폴더안에 포함된 파일 이름에 폴더명 있으면 제거

2022-08-05 06:43 UTC, bbeomjin commented on models/Reference/A2C/a2c_load_play.py
> +    main()
Adding a new line at end of line

2022-08-05 06:47 UTC, bbeomjin commented on models/Reference/A2C/a2c_load_play.py
> +    main()
How to modify this file directly?

2022-08-05 11:05 UTC, bbeomjin commented
I can not pull these codes. 
How can I get?

2022-08-05 13:27 UTC, rockgoat95 commented
아 ! 여기 있네요

2022-08-06 03:46 UTC, RektPunk approved these changes
일단 merge 하고 다시 변경해볼게~

2022-08-06 03:47 UTC, merged