Feature/beom init
ReportFxxkingMan/MessyRL pull request #16
Opened 2022-09-19 07:43 UTC by bbeomjin

## What does this PR do?

## How to test this? 
- 

## Does anything else need to be done?
-

2022-09-19 07:48 UTC, RektPunk requested changes

2022-09-19 07:48 UTC, RektPunk commented on module/common/replaybuffer.py
> +        self.buffer_size = capacity
why you add this?

2022-09-19 07:48 UTC, RektPunk commented on module/schemas/common.py
> +    state: np.ndarray
isn't it list of np.ndarray?
For example,
```
state: List[np.ndarray]
```

2022-09-19 07:48 UTC, RektPunk commented on module/schemas/common.py
> +    class Config:
How bout set this in Optional?

2022-09-19 08:06 UTC, RektPunk requested changes

2022-09-19 08:06 UTC, RektPunk commented on module/schemas/common.py
> +    state: np.ndarray
Also, float and np.ndarray are compatible.

2022-09-19 12:01 UTC, bbeomjin commented on module/common/replaybuffer.py
> +        self.buffer_size = capacity
Because buffer_size variable is used in "add()" method in line 38

2022-09-19 15:28 UTC, RektPunk approved these changes
gogo

2022-09-20 00:15 UTC, rockgoat95 commented
엄지척 bb

2022-09-20 04:19 UTC, merged