add custom Gym environment example
ReportFxxkingMan/MessyRL pull request #8
Opened 2022-08-18 14:25 UTC by rockgoat95

## What does this PR do?
-  Custom gym 생성 예제코드 첨부합니다. 업비트의 이더리움 가격의 양봉/음봉, 볼륨을 보고 구매/판매를 결정하는 환경입니다. 이러한 틀에 맞추어서 코드를 짜면 StableBaselines3와 같은 RL 라이브러리에도 연동이 가능합니다. 

## How to test this? 
-  action에 따른 아웃풋 값들이 정상적으로 도출되는 것을 확인했습니다. 

## Does anything else need to be done?
-  예제로 올린 환경이라, 전부 구매, 전부 판매 밖에 안되요. 세부적인 리스크 관리 같은 부분이 들어간다면 더욱 좋은 환경이 될 것 같네요. 이제 전에 올려주신 부분과 RL 알고리즘 수정해야 할 부분 찾아볼게요 늦어서 죄송합니다 ㅠ

2022-08-20 03:37 UTC, RektPunk requested changes
reorganize 및 사소한 수정
- @rockgoat95, tests/ 에 있던 코드를 environment/ 로 이동했음
- Upbit_Env를 UpbitEnv 로 변경했음
- data_ETH를 data_eth 로 변경했음

요청 사항
- doc string... 넣어줘..

2022-08-20 03:37 UTC, RektPunk commented on environment/upbit.py
> +    """
doc string 으로 class 가 뭐하는 녀석인지 추가해줘..!

2022-08-20 03:37 UTC, RektPunk commented on environment/upbit.py
> +        """
doc string

2022-08-20 03:37 UTC, RektPunk commented on environment/upbit.py
> +        """
doc string

2022-08-21 13:33 UTC, rockgoat95 commented on environment/upbit.py
> +    """
넵 알겠습니다!

2022-08-24 13:33 UTC, rockgoat95 commented
docstring 달아뒀습니다. 그리고  코드 조금 수정했고, StableBaselines3 라이브러리 써서 실행되는 것도 확인했어요 ! 지금 있는 알고리즘들이 다 틀이 특정환경에 맞게 구현되있어서 현재코드로 테스트하긴 힘들어서 라이브러리 사용해서 테스트했어요.

2022-08-26 14:52 UTC, RektPunk commented on environment/upbit.py
> +
```suggestion

```

2022-08-26 14:53 UTC, RektPunk commented on environment/upbit.py
> +        return None
```suggestion
        return None

```

2022-08-26 14:53 UTC, RektPunk approved these changes
Awesome!

2022-08-26 14:55 UTC, merged